mikk-mmc-web/Models/Shared/ConnectionStatus.cs
namespace mikk_mmc_web.Models.Shared
{
    /// <summary>
    /// Defines the connection status for a router device
    /// </summary>
    public enum ConnectionStatus
    {
        /// <summary>
        /// The device is disconnected
        /// </summary>
        Disconnected,
        
        /// <summary>
        /// The device is connecting
        /// </summary>
        Connecting,
        
        /// <summary>
        /// The device is connected
        /// </summary>
        Connected,
        
        /// <summary>
        /// The device is disconnecting
        /// </summary>
        Disconnecting,
        
        /// <summary>
        /// The connection to the device failed
        /// </summary>
        Failed
    }
}

mikk-mmc-web/Models/Shared/DataPoint.cs
using System;

namespace MikroTikMonitor.Models
{
    /// <summary>
    /// Represents a data point for charts
    /// </summary>
    public struct DataPoint
    {
        /// <summary>
        /// Gets the time of the data point
        /// </summary>
        public DateTime Time { get; }
        
        /// <summary>
        /// Gets the value of the data point
        /// </summary>
        public double Value { get; }
        
        /// <summary>
        /// Initializes a new instance of the DataPoint struct
        /// </summary>
        /// <param name="time">The time of the data point</param>
        /// <param name="value">The value of the data point</param>
        public DataPoint(DateTime time, double value)
        {
            Time = time;
            Value = value;
        }
    }
}

mikk-mmc-web/Models/Shared/DhcpLease.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace MikroTikMonitor.Models
{
    public class DhcpLease : ModelBase
    {
        private string _id;
        private string _address;
        private string _macAddress;
        private string _clientId;
        private string _hostName;
        private string _comment;
        private bool _isDynamic;
        private DateTime _expiryTime;
        private DateTime _lastSeen;
        private string _server;
        private string _status;

        public string Id 
        { 
            get => _id; 
            set => SetProperty(ref _id, value); 
        }
        
        public string Address 
        { 
            get => _address; 
            set => SetProperty(ref _address, value); 
        }
        
        public string MacAddress 
        { 
            get => _macAddress; 
            set => SetProperty(ref _macAddress, value); 
        }
        
        public string ClientId 
        { 
            get => _clientId; 
            set => SetProperty(ref _clientId, value); 
        }
        
        public string HostName 
        { 
            get => _hostName; 
            set => SetProperty(ref _hostName, value); 
        }
        
        public string Comment 
        { 
            get => _comment; 
            set => SetProperty(ref _comment, value); 
        }
        
        public bool IsDynamic 
        { 
            get => _isDynamic; 
            set => SetProperty(ref _isDynamic, value); 
        }
        
        public DateTime ExpiryTime 
        { 
            get => _expiryTime; 
            set => SetProperty(ref _expiryTime, value); 
        }
        
        public DateTime LastSeen 
        { 
            get => _lastSeen; 
            set => SetProperty(ref _lastSeen, value); 
        }
        
        public string Server 
        { 
            get => _server; 
            set => SetProperty(ref _server, value); 
        }
        
        public string Status 
        { 
            get => _status; 
            set => SetProperty(ref _status, value); 
        }
    }
}

mikk-mmc-web/Models/Shared/FirewallRule.cs
using System;

namespace mikk_mmc_web.Models.Shared
{
    /// <summary>
    /// Represents a firewall rule on a router device
    /// </summary>
    public class FirewallRule : ModelBase
    {
        private string _id;
        private string _chain;
        private string _action;
        private string _srcAddress;
        private string _dstAddress;
        private string _protocol;
        private string _srcPort;
        private string _dstPort;
        private string _inInterface;
        private string _outInterface;
        private string _comment;
        private bool _isEnabled;
        private int _order;

        /// <summary>
        /// Gets or sets the identifier of the rule
        /// </summary>
        public string Id
        {
            get => _id;
            set => SetProperty(ref _id, value);
        }

        /// <summary>
        /// Gets or sets the chain of the rule
        /// </summary>
        public string Chain
        {
            get => _chain;
            set => SetProperty(ref _chain, value);
        }

        /// <summary>
        /// Gets or sets the action of the rule
        /// </summary>
        public string Action
        {
            get => _action;
            set => SetProperty(ref _action, value);
        }

        /// <summary>
        /// Gets or sets the source address of the rule
        /// </summary>
        public string SrcAddress
        {
            get => _srcAddress;
            set => SetProperty(ref _srcAddress, value);
        }

        /// <summary>
        /// Gets or sets the destination address of the rule
        /// </summary>
        public string DstAddress
        {
            get => _dstAddress;
            set => SetProperty(ref _dstAddress, value);
        }

        /// <summary>
        /// Gets or sets the protocol of the rule
        /// </summary>
        public string Protocol
        {
            get => _protocol;
            set => SetProperty(ref _protocol, value);
        }

        /// <summary>
        /// Gets or sets the source port of the rule
        /// </summary>
        public string SrcPort
        {
            get => _srcPort;
            set => SetProperty(ref _srcPort, value);
        }

        /// <summary>
        /// Gets or sets the destination port of the rule
        /// </summary>
        public string DstPort
        {
            get => _dstPort;
            set => SetProperty(ref _dstPort, value);
        }

        /// <summary>
        /// Gets or sets the in interface of the rule
        /// </summary>
        public string InInterface
        {
            get => _inInterface;
            set => SetProperty(ref _inInterface, value);
        }

        /// <summary>
        /// Gets or sets the out interface of the rule
        /// </summary>
        public string OutInterface
        {
            get => _outInterface;
            set => SetProperty(ref _outInterface, value);
        }

        /// <summary>
        /// Gets or sets the comment of the rule
        /// </summary>
        public string Comment
        {
            get => _comment;
            set => SetProperty(ref _comment, value);
        }

        /// <summary>
        /// Gets or sets whether the rule is enabled
        /// </summary>
        public bool IsEnabled
        {
            get => _isEnabled;
            set => SetProperty(ref _isEnabled, value);
        }

        /// <summary>
        /// Gets or sets the order of the rule
        /// </summary>
        public int Order
        {
            get => _order;
            set => SetProperty(ref _order, value);
        }
    }
}

mikk-mmc-web/Models/Shared/InterfaceTraffic.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace MikroTikMonitor.Models
{
    public class InterfaceTraffic : ModelBase
    {
        private DateTime _timestamp;
        private long _rxBytes;
        private long _txBytes;
        private long _rxPackets;
        private long _txPackets;
        private long _rxErrors;
        private long _txErrors;
        private long _rxDrops;
        private long _txDrops;

        public DateTime Timestamp 
        { 
            get => _timestamp; 
            set => SetProperty(ref _timestamp, value); 
        }
        
        public long RxBytes 
        { 
            get => _rxBytes; 
            set => SetProperty(ref _rxBytes, value); 
        }
        
        public long TxBytes 
        { 
            get => _txBytes; 
            set => SetProperty(ref _txBytes, value); 
        }
        
        public long RxPackets 
        { 
            get => _rxPackets; 
            set => SetProperty(ref _rxPackets, value); 
        }
        
        public long TxPackets 
        { 
            get => _txPackets; 
            set => SetProperty(ref _txPackets, value); 
        }
        
        public long RxErrors 
        { 
            get => _rxErrors; 
            set => SetProperty(ref _rxErrors, value); 
        }
        
        public long TxErrors 
        { 
            get => _txErrors; 
            set => SetProperty(ref _txErrors, value); 
        }
        
        public long RxDrops 
        { 
            get => _rxDrops; 
            set => SetProperty(ref _rxDrops, value); 
        }
        
        public long TxDrops 
        { 
            get => _txDrops; 
            set => SetProperty(ref _txDrops, value); 
        }
    }
}

mikk-mmc-web/Models/Shared/LogEntry.cs
using System;

namespace mikk_mmc_web.Models.Shared
{
    /// <summary>
    /// Represents a log entry from a router device
    /// </summary>
    public class LogEntry : ModelBase
    {
        private string _id;
        private DateTime _timestamp;
        private string _facility;
        private string _topic;
        private string _message;
        private LogSeverity _severity;

        /// <summary>
        /// Gets or sets the identifier of the log entry
        /// </summary>
        public string Id
        {
            get => _id;
            set => SetProperty(ref _id, value);
        }

        /// <summary>
        /// Gets or sets the timestamp of the log entry
        /// </summary>
        public DateTime Timestamp
        {
            get => _timestamp;
            set => SetProperty(ref _timestamp, value);
        }

        /// <summary>
        /// Gets or sets the facility of the log entry
        /// </summary>
        public string Facility
        {
            get => _facility;
            set => SetProperty(ref _facility, value);
        }

        /// <summary>
        /// Gets or sets the topic of the log entry
        /// </summary>
        public string Topic
        {
            get => _topic;
            set => SetProperty(ref _topic, value);
        }

        /// <summary>
        /// Gets or sets the message of the log entry
        /// </summary>
        public string Message
        {
            get => _message;
            set => SetProperty(ref _message, value);
        }

        /// <summary>
        /// Gets or sets the severity of the log entry
        /// </summary>
        public LogSeverity Severity
        {
            get => _severity;
            set => SetProperty(ref _severity, value);
        }

        /// <summary>
        /// Gets a CSS class for the log severity
        /// </summary>
        public string SeverityClass
        {
            get
            {
                return Severity switch
                {
                    LogSeverity.Debug => "debug",
                    LogSeverity.Info => "info",
                    LogSeverity.Warning => "warning",
                    LogSeverity.Error => "error",
                    LogSeverity.Critical => "critical",
                    _ => "unknown"
                };
            }
        }
    }
}

mikk-mmc-web/Models/Shared/ModelBase.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace mikk_mmc_web.Models.Shared
{
    /// <summary>
    /// Base class for models that support property change notification
    /// </summary>
    public abstract class ModelBase : INotifyPropertyChanged
    {
        /// <summary>
        /// Property changed event
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Set property value and raise property changed event if changed
        /// </summary>
        /// <typeparam name="T">Type of property</typeparam>
        /// <param name="storage">Reference to backing field</param>
        /// <param name="value">New value</param>
        /// <param name="propertyName">Name of property</param>
        /// <returns>True if property was changed</returns>
        protected bool SetProperty<T>(ref T storage, T value, [CallerMemberName] string propertyName = null)
        {
            if (EqualityComparer<T>.Default.Equals(storage, value))
                return false;

            storage = value;
            OnPropertyChanged(propertyName);
            return true;
        }

        /// <summary>
        /// Raise property changed event
        /// </summary>
        /// <param name="propertyName">Name of property</param>
        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}

mikk-mmc-web/Controllers/RouterController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mikk_mmc_web.Models;
using mikk_mmc_web.Services;
using System;
using System.Threading.Tasks;

namespace mikk_mmc_web.Controllers
{
    public class RouterController : Controller
    {
        private readonly ILogger<RouterController> _logger;
        private readonly IRouterService _routerService;

        public RouterController(ILogger<RouterController> logger, IRouterService routerService)
        {
            _logger = logger;
            _routerService = routerService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                if (!_routerService.IsConnected)
                {
                    return View("NotConnected");
                }

                var routerInfo = await _routerService.GetRouterInfoAsync();
                var resources = await _routerService.GetSystemResourcesAsync();

                ViewBag.SystemResources = resources;
                return View(routerInfo);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Lỗi khi lấy thông tin Router");
                ViewBag.ErrorMessage = "Có lỗi xảy ra khi tải thông tin Router. Chi tiết: " + ex.Message;
                return View("Error");
            }
        }

        [HttpGet]
        public IActionResult Connect()
        {
            return View(new ConnectionSettings());
        }

        [HttpPost]
        public async Task<IActionResult> Connect(ConnectionSettings settings)
        {
            if (!ModelState.IsValid)
            {
                return View(settings);
            }

            try
            {
                var success = await _routerService.ConnectAsync(settings);
                if (success)
                {
                    _logger.LogInformation("Đã kết nối thành công đến Router {IpAddress}", settings.IpAddress);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Không thể kết nối đến Router. Vui lòng kiểm tra lại thông tin đăng nhập.");
                    return View(settings);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Lỗi khi kết nối đến Router {IpAddress}", settings.IpAddress);
                ModelState.AddModelError("", "Lỗi khi kết nối: " + ex.Message);
                return View(settings);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Disconnect()
        {
            try
            {
                await _routerService.DisconnectAsync();
                return RedirectToAction("Connect");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Lỗi khi ngắt kết nối Router");
                ViewBag.ErrorMessage = "Có lỗi xảy ra khi ngắt kết nối Router. Chi tiết: " + ex.Message;
                return View("Error");
            }
        }

        [HttpGet]
        public async Task<IActionResult> SystemResources()
        {
            try
            {
                if (!_routerService.IsConnected)
                {
                    return View("NotConnected");
                }

                var resources = await _routerService.GetSystemResourcesAsync();
                return View(resources);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Lỗi khi lấy tài nguyên hệ thống");
                ViewBag.ErrorMessage = "Có lỗi xảy ra khi tải tài nguyên hệ thống. Chi tiết: " + ex.Message;
                return View("Error");
            }
        }
    }
}

mikk-mmc-web/Views/Shared/NotConnected.cshtml
@{
    ViewData["Title"] = "Chưa kết nối";
}

<div class="text-center">
    <div class="alert alert-warning">
        <h3><i class="bi bi-exclamation-triangle"></i> Chưa kết nối đến Router</h3>
        <p>Bạn cần kết nối đến một Router MikroTik để sử dụng chức năng này.</p>
    </div>

    <div class="mt-4">
        <a href="@Url.Action("Connect", "Router")" class="btn btn-primary">
            <i class="bi bi-power"></i> Kết nối ngay
        </a>
    </div>
</div>

mikk-mmc-web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MikroTik Monitor Web</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">
                    <i class="bi bi-router-fill"></i> MikroTik Monitor
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Home" && ViewContext.RouteData.Values["Action"].ToString() == "Index" ? "active" : "")" 
                               href="@Url.Action("Index", "Home")">
                                <i class="bi bi-house"></i> Trang chủ
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Router" ? "active" : "")" 
                               href="@Url.Action("Index", "Router")">
                                <i class="bi bi-router"></i> Trạng thái Router
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Interface" ? "active" : "")" 
                               href="@Url.Action("Index", "Interface")">
                                <i class="bi bi-ethernet"></i> Giao diện mạng
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Firewall" ? "active" : "")" 
                               href="@Url.Action("Index", "Firewall")">
                                <i class="bi bi-shield-check"></i> Tường lửa
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Dhcp" ? "active" : "")" 
                               href="@Url.Action("Index", "Dhcp")">
                                <i class="bi bi-diagram-3"></i> DHCP
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Log" ? "active" : "")" 
                               href="@Url.Action("Index", "Log")">
                                <i class="bi bi-journal-text"></i> Nhật ký
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="d-flex">
                    @if (ViewBag.IsConnected == true)
                    {
                        <form method="post" action="@Url.Action("Disconnect", "Router")">
                            <button type="submit" class="btn btn-outline-light">
                                <i class="bi bi-power"></i> Ngắt kết nối
                            </button>
                        </form>
                    }
                    else
                    {
                        <a href="@Url.Action("Connect", "Router")" class="btn btn-outline-light">
                            <i class="bi bi-power"></i> Kết nối Router
                        </a>
                    }
                </div>
            </div>
        </nav>
    </header>

    <div class="container mt-4">
        @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
        {
            <div class="alert alert-danger">
                <i class="bi bi-exclamation-triangle"></i> @ViewBag.ErrorMessage
            </div>
        }
        
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - MikroTik Monitor Web - <a href="https://github.com/username/mikk-mmc-web">GitHub</a>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.7.1/dist/chart.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>